#!/bin/bash

# 🔐 CyberPort - Portfolio de Ciberseguridad
# Script de bienvenida e inicio rápido

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                  🔐 CYBERPORT INICIADO 🔐                  ║"
echo "║          Tu Portfolio de Ciberseguridad en Vercel          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ PROYECTO CREADO EXITOSAMENTE"
echo ""
echo "📁 Ubicación:"
echo "   /Users/julichaan/Documents/julichaan-portfolio"
echo ""
echo "🎯 PRÓXIMOS PASOS:"
echo ""
echo "1️⃣  Ir al directorio:"
echo "    cd /Users/julichaan/Documents/julichaan-portfolio"
echo ""
echo "2️⃣  Instalar dependencias (si aún no lo hiciste):"
echo "    npm install"
echo ""
echo "3️⃣  Ejecutar servidor de desarrollo:"
echo "    npm run dev"
echo ""
echo "4️⃣  Abre en tu navegador:"
echo "    http://localhost:5173/"
echo ""
echo "📚 GUÍAS DISPONIBLES:"
echo ""
echo "   • QUICKSTART.md         - Inicio rápido en 5 minutos"
echo "   • PERSONALIZATION.md    - Cómo personalizar tu sitio"
echo "   • VERCEL_DEPLOYMENT.md  - Desplegar en Vercel"
echo "   • README.md             - Documentación completa"
echo ""
echo "🎨 CARACTERÍSTICAS INCLUIDAS:"
echo ""
echo "   ✓ Tema oscuro moderno inspirado en m33n4n"
echo "   ✓ Terminal interactiva con efecto typing"
echo "   ✓ Blog dinámico con categorías"
echo "   ✓ Páginas: Home, Blog, Artículos, About, Contacto"
echo "   ✓ Animaciones y efectos hover"
echo "   ✓ Diseño responsive (mobile-first)"
echo "   ✓ Listo para Vercel (un clic para desplegar)"
echo ""
echo "💡 TIPS:"
echo ""
echo "   • Personaliza en: src/data/articles.js"
echo "   • Agrega tu email en: Contact.vue"
echo "   • Tus redes en: About.vue"
echo "   • Cambia colores en: tailwind.config.js"
echo ""
echo "🚀 DESPLEGAR:"
echo ""
echo "   1. Crea un repositorio en GitHub"
echo "   2. Sube tu código:"
echo "      git init && git add . && git commit -m 'Initial commit'"
echo "      git remote add origin https://github.com/TU_USUARIO/julichaan-portfolio"
echo "      git push -u origin main"
echo ""
echo "   3. Ve a vercel.com y conecta tu repositorio"
echo "   4. ¡Vercel desplegará automáticamente!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "¿Necesitas ayuda? Revisa los archivos .md incluidos"
echo ""
echo "¡Bienvenido a CyberPort! 🔐✨"
echo ""
